fix: Replace table instead of dropping and renaming for BigQuery
fal-ai/fal pull request #369
Opened 2022-06-08 21:48 UTC by chamini2

This avoids getting a 404 error and then creating, which sometimes is cached by the BigQuery service and then reports a 404 even when the table has just been created.

https://github.com/googleapis/google-cloud-go/issues/975#issuecomment-383294334
> I think you answered your own question. Creating a table is an eventually consistent operation: it may not appear to exist everywhere until after some time has passed. In the screenshots above, the second request, which happens 2 seconds after the first, may end up at a different location where the creation hasn't yet propagated.

2022-06-08 21:52 UTC, chamini2 commented
https://github.com/fal-ai/fal/actions/runs/2464595265

2022-06-09 07:39 UTC, mederka requested changes
Great solution. Much better than setting a timer.

2022-06-09 07:39 UTC, mederka commented on .github/workflows/test_profiles.yml
> -        profile: ["postgres", "bigquery", "snowflake", "redshift", "duckdb"]
Might need to bring this back before merging.

2022-06-09 16:37 UTC, chamini2 commented
https://github.com/fal-ai/fal/actions/runs/2469745557

2022-06-10 15:38 UTC, mederka approved these changes
Looks good!

2022-06-10 15:39 UTC, merged