docs: Compatibility document
fal-ai/fal pull request #467
Opened 2022-07-19 14:45 UTC by isidentical

2022-07-19 15:46 UTC, chamini2 requested changes

2022-07-19 15:46 UTC, chamini2 commented on docsite/docs/Docs/compatibility.md
> +|     | Fal Version | Supported DBT Version        |
use lower case for dbt and fal throughout the doc

2022-07-19 15:51 UTC, chamini2 commented on docsite/docs/Docs/compatibility.md
> +Please note that `post-hook`s can not be individually selected/run, so you have
`can not` -> `cannot`

2022-07-19 15:51 UTC, chamini2 commented on docsite/docs/Docs/compatibility.md
> +time. If you need to select and run specific scripts, the current workaround is
I don't know if we want to give a hack around this or maybe try to address it and document it once we have a good solution.

2022-07-19 17:08 UTC, chamini2 approved these changes

2022-07-19 17:08 UTC, chamini2 commented on docsite/docs/Docs/compatibility.md
> +them to individual ["Python models"](/Guides/python-models-migration).
great!

2022-07-20 16:04 UTC, burkaygur approved these changes

2022-07-22 08:16 UTC, merged